using Store.Statics;
using Store.Structs;
using Store.UserForms.EmailForms;

namespace Store.LoginAndRegister
{
    public partial class Register : Form
    {
        public Register()
        {
            InitializeComponent();

            FormClosing += Program.store.CloseEnvironment;
            BackButton.Click += BackButton_Click;

            RegisterButton.Click += RegisterButton_Click;
        }

        private void RegisterButton_Click(object? sender, EventArgs e)
        {
            // Validate different fields with their respective inputs
            bool isFirstNameValid = Validation.ValidateName(firstNameTextBox.Text.ToString().Trim());
            bool isLastNameValid = Validation.ValidateName(lastNameTextBox.Text.ToString().Trim());
            bool isPhoneNumberValid = Validation.ValidatePhoneNumber(phoneNumberTextBox.Text.ToString().Trim());
            bool isEmailValid = Validation.ValidateEmail(emailTextBox.Text.ToString().Trim());
            bool isUsernameValid = Validation.ValidateUsername(usernameTextBox.Text.ToString().Trim());
            bool isPasswordValid = Validation.ValidatePassword(passwordTextBox.Text.ToString().Trim());
            bool isUsernameUnique = Program.store.dataParser.CheckUniqueUsername(usernameTextBox.Text.ToString().Trim());

            if (isFirstNameValid && isLastNameValid && isPhoneNumberValid && isEmailValid && isUsernameValid && isPasswordValid && isUsernameUnique)
            {
                UserData registeredUser = new UserData(
                    (int)UserRoles.Customer,
                    Program.store.dataParser.GenerateAutoGeneratedUserId(),
                    usernameTextBox.Text.ToString().Trim(),
                    passwordTextBox.Text.ToString().Trim(),
                    firstNameTextBox.Text.ToString().Trim(),
                    lastNameTextBox.Text.ToString().Trim(),
                    emailTextBox.Text.ToString().Trim(),
                    phoneNumberTextBox.Text.ToString().Trim()
                    );

                Program.store.dataParser.AddUser(registeredUser);

                MessageBox.Show("Successfully Registered User\nYou can now Login!", "Registration Success", MessageBoxButtons.OK);

                RegisterNotificaiton registerNotificaiton = (RegisterNotificaiton)new RegisterNotificaiton(registeredUser).SetDialogProperties();
                registerNotificaiton.ShowDialog();

                this.Hide();

                Login login = (Login)new Login().SetFormProperties(this);
                login.Show();
                login.Focus();
            }
            else
            {
                if (!isFirstNameValid)
                    MessageBox.Show("First Name is not Valid.\nName should not be empty and should only contain letters.", "Validation Error", MessageBoxButtons.OK);
                else if (!isLastNameValid)
                    MessageBox.Show("Last Name is not Valid.\nName should not be empty and should only contain letters.", "Validation Error", MessageBoxButtons.OK);
                else if (!isPhoneNumberValid)
                    MessageBox.Show("Phone Number is not Valid.", "Validation Error", MessageBoxButtons.OK);
                else if (!isEmailValid)
                    MessageBox.Show("Email is not Valid.", "Validation Error", MessageBoxButtons.OK);
                else if (!isUsernameValid)
                    MessageBox.Show("Username is not Valid.\nUsername should not be empty and should only contain letters, numbers, and underscores.", "Validation Error", MessageBoxButtons.OK);
                else if (!isPasswordValid)
                    MessageBox.Show("Password is not Valid.\nPassword should not empty and has at least 8 characters.", "Validation Error", MessageBoxButtons.OK);
                else if (!isUsernameUnique)
                    MessageBox.Show("Username already exists, please pick a new username.", "Validation Error", MessageBoxButtons.OK);
            }
        }
        private void BackButton_Click(object? sender, EventArgs e)
        {
            this.Hide();
            Program.store.ShowHomePage(this);
        }
    }
}
