using Store.Structs;
using Store.UserMenus;
using System.Data;

namespace Store.UserForms.StaffSubForms
{
    public partial class ItemsForm : Form
    {
        public ItemsForm()
        {
            InitializeComponent();

            FormClosing += Program.store.CloseEnvironment;
            BackButton.Click += BackButton_Click;

            InitializeListView();

            if (Program.store.userData.UserRole.Equals(UserRoles.Admin))
            {
                InitializeAddTab();
                InitializeEditTab();
                InitializeDeleteTab();
            }
            else
            {
                tabControl1.TabPages[1].Enabled = false;
                tabControl1.TabPages[2].Enabled = false;
                tabControl1.TabPages[3].Enabled = false;
            }

        }

        private void BackButton_Click(object? sender, EventArgs e)
        {
            if (Program.store.userData.UserRole.Equals(UserRoles.Admin))
            {
                this.Hide();

                AdminForm form = (AdminForm)new AdminForm().SetFormProperties(this);
                form.Show();
                form.Focus();
            }
            else if (Program.store.userData.UserRole.Equals(UserRoles.Employee))
            {
                this.Hide();

                EmployeeForm form = (EmployeeForm)new EmployeeForm().SetFormProperties(this);
                form.Show();
                form.Focus();
            }
            else if (Program.store.userData.UserRole.Equals(UserRoles.Packager))
            {
                this.Hide();

                PackagerForm form = (PackagerForm)new PackagerForm().SetFormProperties(this);
                form.Show();
                form.Focus();
            }
            else
            {
                throw new Exception("Users that are not admin or employee should never be here");
            }
        }


        /// <summary>
        /// Initializes List View Coloumns and Details
        /// </summary>
        private void InitializeListView()
        {
            toolStripTextBox1.TextChanged += ToolStripTextBox1_TextChanged;
            toolStripDropDownButton1.DropDownItemClicked += ToolStripDropDownButton1_Click;

            listView1.View = View.Details;

            listView1.Groups.Clear();
            toolStripDropDownButton1.DropDown.Items.Clear();

            toolStripDropDownButton1.DropDown.Items.Add("View All");

            foreach (ItemCategories categories in Enum.GetValues(typeof(ItemCategories)))
            {
                listView1.Groups.Add(new ListViewGroup(categories.ToString(), HorizontalAlignment.Left));
                toolStripDropDownButton1.DropDown.Items.Add(categories.ToString());
            }

            listView1.Columns.Clear();
            listView1.Columns.Add("Item Id", 100);
            listView1.Columns.Add("Item Name", 300);
            listView1.Columns.Add("Item Price", 100);
            listView1.Columns.Add("Description", 200);

            InitializeListViewItems();
        }

        /// <summary>
        /// Repopulates list of items
        /// </summary>
        private void InitializeListViewItems()
        {
            listView1.Items.Clear();

            foreach (var itemData in Program.store.dataParser.itemDataList)
            {
                ListViewItem item = new ListViewItem(itemData.itemId.ToString());

                item.SubItems.Add(itemData.itemName.ToString());
                item.SubItems.Add($"{itemData.itemPrice:C}");
                item.SubItems.Add($"{itemData.itemDescription}");

                item.Group = listView1.Groups[((int)itemData.itemCategory) - 1];

                listView1.Items.Add(item);
            }
        }

        /// <summary>
        /// Add Tab
        /// </summary>
        private void InitializeAddTab()
        {
            AddButton.Click += AddButton_Click;
            addItemComboBox.Items.Clear();

            foreach (ItemCategories categories in Enum.GetValues(typeof(ItemCategories)))
            {
                addItemComboBox.Items.Add(categories.ToString());
            }
        }

        private void AddButton_Click(object? sender, EventArgs e)
        {
            ItemData newItem = new ItemData(
                addItemComboBox.SelectedIndex + 1,
                Program.store.dataParser.GetAutoGeneratedItemId(),
                addItemNameTextBox.Text.ToString().Trim(),
                Convert.ToDouble(addPriceTextBox.Text.ToString().Trim()),
                addItemDescriptionTextBox.Text.ToString().Trim()
            );

            string mbString = $"Are you sure you want to add this new item?\n" +
                $"Item Category: {newItem.itemCategory.ToString()}\n" +
                $"Item Id: {newItem.itemId}\n" +
                $"Item Name: {newItem.itemName}\n" +
                $"Item Price: {newItem.itemPrice:C}\n" +
                $"Item Description: {newItem.itemDescription}";

            DialogResult dialogResult = MessageBox.Show(mbString, "Add Item", MessageBoxButtons.YesNo);

            if (dialogResult == DialogResult.Yes)
            {
                Program.store.dataParser.AddItem(newItem);

                addItemNameTextBox.Text = "";
                addPriceTextBox.Text = "";
                addItemDescriptionTextBox.Text = "";

                InitializeListViewItems();
            }
        }

        /// <summary>
        /// Edit Tab
        /// </summary>
        private void InitializeEditTab()
        {
            editSearchTextBox.TextChanged += EditSearchTextBox_TextChanged;

            editApplyButton.Click += EditApplyButton_Click;
            editCancelButton.Click += EditCancelButton_Click;


            editCatergoryComboBox.Items.Clear();

            foreach (ItemCategories categories in Enum.GetValues(typeof(ItemCategories)))
            {
                editCatergoryComboBox.Items.Add(categories.ToString());
            }
        }

        private void EditSearchTextBox_TextChanged(object? sender, EventArgs e)
        {
            string newInput = editSearchTextBox.Text;

            if (!string.IsNullOrEmpty(newInput))
            {
                foreach (ItemData item in Program.store.dataParser.itemDataList)
                {
                    if (item.itemId.Equals(newInput.ToLower()))
                    {
                        editApplyButton.Enabled = true;
                        editCancelButton.Enabled = true;

                        editCatergoryComboBox.SelectedIndex = ((int)item.itemCategory) - 1;
                        editItemIdTextBox.Text = item.itemId.ToString();
                        editNameTextBox.Text = item.itemName.ToString();
                        editDescriptionTextBox.Text = item.itemDescription.ToString();
                        editPriceTextBox.Text = $"{item.itemPrice}";

                        return;
                    }
                }
            }

            editApplyButton.Enabled = false;
            editCancelButton.Enabled = false;

            editCatergoryComboBox.SelectedIndex = 0;
            editItemIdTextBox.Text = string.Empty;
            editNameTextBox.Text = string.Empty;
            editDescriptionTextBox.Text = string.Empty;
            editPriceTextBox.Text = string.Empty;
        }

        private void EditCancelButton_Click(object? sender, EventArgs e)
        {
            string newInput = editSearchTextBox.Text;

            if (!string.IsNullOrEmpty(newInput))
            {
                foreach (ItemData item in Program.store.dataParser.itemDataList)
                {
                    if (item.itemId.Equals(newInput.ToLower()))
                    {
                        editApplyButton.Enabled = true;
                        editCancelButton.Enabled = true;

                        editCatergoryComboBox.SelectedIndex = ((int)item.itemCategory) - 1;
                        editItemIdTextBox.Text = item.itemId.ToString();
                        editNameTextBox.Text = item.itemName.ToString();
                        editDescriptionTextBox.Text = item.itemDescription.ToString();
                        editPriceTextBox.Text = $"{item.itemPrice}";

                        return;
                    }
                }
            }
        }
        private void EditApplyButton_Click(object? sender, EventArgs e)
        {
            DialogResult dialogResult = MessageBox.Show("Are you sure you want to edit this item?", "Edit Item", MessageBoxButtons.YesNo);

            if (dialogResult == DialogResult.Yes)
            {
                ItemData newItem = new ItemData(
                    editCatergoryComboBox.SelectedIndex + 1,
                    editItemIdTextBox.Text.ToString().Trim(),
                    editNameTextBox.Text.ToString().Trim(),
                    Convert.ToDouble(editPriceTextBox.Text.ToString().Trim()),
                    editDescriptionTextBox.Text.ToString().Trim()
                );

                Program.store.dataParser.EditItem(newItem);
                InitializeListViewItems();
            }
        }

        /// <summary>
        /// Delete Tab
        /// </summary>
        private void InitializeDeleteTab()
        {
            deleteItemSearchTextBox.TextChanged += DeleteItemSearchTextBox_TextChanged; ;

            deleteItemButton.Click += DeleteItemButton_Click;


            deleteCatergoryComboBox.Items.Clear();

            foreach (ItemCategories categories in Enum.GetValues(typeof(ItemCategories)))
            {
                deleteCatergoryComboBox.Items.Add(categories.ToString());
            }
        }

        private void DeleteItemSearchTextBox_TextChanged(object? sender, EventArgs e)
        {
            string newInput = deleteItemSearchTextBox.Text;

            if (!string.IsNullOrEmpty(newInput))
            {
                foreach (ItemData item in Program.store.dataParser.itemDataList)
                {
                    if (item.itemId.Equals(newInput.ToLower()))
                    {
                        deleteItemButton.Enabled = true;

                        deleteCatergoryComboBox.SelectedIndex = ((int)item.itemCategory) - 1;
                        deleteItemIdTextBox.Text = item.itemId.ToString();
                        deleteItemNameTextBox.Text = item.itemName.ToString();
                        deleteItemDescriptionTextBox.Text = item.itemDescription.ToString();
                        deleteItemPriceTextBox.Text = $"{item.itemPrice}";

                        return;
                    }
                }
            }

            deleteItemButton.Enabled = false;

            deleteCatergoryComboBox.SelectedIndex = 0;
            deleteItemIdTextBox.Text = string.Empty;
            deleteItemNameTextBox.Text = string.Empty;
            deleteItemDescriptionTextBox.Text = string.Empty;
            deleteItemPriceTextBox.Text = string.Empty;
        }

        private void DeleteItemButton_Click(object? sender, EventArgs e)
        {
            DialogResult dialogResult = MessageBox.Show("Are you sure you want to delete this item?", "Delete Item", MessageBoxButtons.YesNo);

            if (dialogResult == DialogResult.Yes)
            {
                Program.store.dataParser.DeleteItemById(deleteItemIdTextBox.Text.ToString().Trim());

                InitializeListViewItems();

                deleteCatergoryComboBox.SelectedIndex = 0;
                deleteItemIdTextBox.Text = string.Empty;
                deleteItemNameTextBox.Text = string.Empty;
                deleteItemDescriptionTextBox.Text = string.Empty;
                deleteItemPriceTextBox.Text = string.Empty;
            }
        }


        /// <summary>
        /// Filters for the specific category
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ToolStripDropDownButton1_Click(object? sender, ToolStripItemClickedEventArgs e)
        {
            InitializeListViewItems();

            if (e.ClickedItem.Text.ToString() == "View All") return;

            listView1.Items.Cast<ListViewItem>()
                .Where(item => item.Group.Header != e.ClickedItem.Text.ToString())
                .ToList()
                .ForEach(item =>
                {
                    listView1.Items.Remove(item);
                });
        }

        /// <summary>
        /// Filters for specfic text
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ToolStripTextBox1_TextChanged(object? sender, EventArgs e)
        {
            string newInput = toolStripTextBox1.Text;

            InitializeListViewItems();

            if (!string.IsNullOrEmpty(newInput))
            {
                listView1.Items.Cast<ListViewItem>()
                    .Where(item => !(item.Text.Contains(newInput) || item.SubItems[1].Text.ToLower().Contains(newInput.ToLower())))
                    .ToList()
                    .ForEach(item =>
                    {
                        listView1.Items.Remove(item);
                    });
            }
        }

    }
}
